#!/usr/bin/bash

httpd &
echo " apache service telah berjalan"

mysqld --defaults-file=$MYSQL_CONFIG\\my.ini --standalone &
echo " mysql service telah berjalan"

(php artisan serve > net.log) &
echo -e " php dev server telah berjalan\n\n message"